---

- hosts: web
  vars_files:
   - defaults/main.yml
  tasks:
    - name: Install unattended-upgrades
      become: yes
      apt:
        name: unattended-upgrades
        state: present

    # # apticron
    # - name: Install apticron
    #   become: yes
    #   apt:
    #     name: apticron
    #     state: present

    - name: Configure unattended-upgrades
      become: yes
      template:
        src: '50unattended-upgrades'
        dest: '/etc/apt/apt.conf.d/50unattended-upgrades'

    - name: Setup unattended-upgrades schedule
      become: yes
      template:
        src: '10periodic'
        dest: '/etc/apt/apt.conf.d/10periodic'

    - name: Restart and Enable unattended-upgrades
      become: yes
      service:
        name: unattended-upgrades
        enabled: true
        state: restarted