---
- hosts: webservers
  become: True
  vars:
    - hostname: "{{ hostname }}.vidoje.rs"

  tasks:
    - name: Update hostname
      hostname:
        name: "{{ hostname }}"

    - name: add hostname to hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: '^127.0.1.1'
        line: "127.0.1.1    {{ hostname }}"
        state: present
