- name: LAMP stack installation for CentOS
  hosts: host1.vidoje.rs, host2.vidoje.rs
  tasks:
        - name: Install Apache
          yum: 
            name: httpd 
            update_cache: yes 
            state: latest
        
        - name: Aktiviranje servisa - APACHE
          service: name=httpd state=started
        
        - name: Instalacija MYSQL - servera
          yum: name=mariadb-server state=latest
        
        - name: Instalacija MYSQL - servera
          yum: name=mariadb state=latest
        
        - name: Pokretanje instalacije
          command: echo -e "\n \ny\nmypass\nmypass\ny\nn\nn\ny" | mysql_secure_installation
       
        - name: Start MYSQL servera
          service: name=mariadb state=restarted
                
        - name: Instalacija PHP-a
          yum: name=php name=php-mysql state=latest
        
        - name: Instalacija vsftpd
          yum: name=vsftpd state=latest
        
        - name: Start FTP-a
          service: name=vsftpd state=started

        - name: Restart APACHE-a
          service: name=httpd state=restarted

